# Generated by Django 5.0.8 on 2024-08-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="assessments",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="assessments.assessment"
            ),
        ),
    ]
