# Generated by Django 5.0.8 on 2024-08-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="customuser_set",
                related_query_name="user",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="customuser_set",
                related_query_name="user",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="accounts.customuser",
            ),
        ),
    ]
