# Generated by Django 5.0.8 on 2024-08-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("assessments", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="lesson_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="courses.lessonplan",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="study_materials",
            field=models.ManyToManyField(
                blank=True, related_name="assessments", to="courses.studymaterial"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="courses.unit",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="accounts.customuser",
            ),
        ),
    ]
